"""empty message

Revision ID: 09d205359da3
Revises: ac8998e570b8
Create Date: 2025-05-16 18:50:27.147172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d205359da3'
down_revision = 'ac8998e570b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('calculations',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('form_input', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('goal',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('wam', sa.Float(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('gpa',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('final_gpa', sa.Float(), nullable=False),
    sa.Column('year_1_semester_1', sa.Float(), nullable=False),
    sa.Column('year_1_semester_2', sa.Float(), nullable=False),
    sa.Column('year_2_semester_1', sa.Float(), nullable=False),
    sa.Column('year_2_semester_2', sa.Float(), nullable=False),
    sa.Column('year_3_semester_1', sa.Float(), nullable=False),
    sa.Column('year_3_semester_2', sa.Float(), nullable=False),
    sa.Column('year_4_semester_1', sa.Float(), nullable=False),
    sa.Column('year_4_semester_2', sa.Float(), nullable=False),
    sa.Column('year_5_semester_1', sa.Float(), nullable=False),
    sa.Column('year_5_semester_2', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('shared_graph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('include_marks', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shared_with_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('wam',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('final_wam', sa.Float(), nullable=False),
    sa.Column('year_1_semester_1', sa.Float(), nullable=False),
    sa.Column('year_1_semester_2', sa.Float(), nullable=False),
    sa.Column('year_2_semester_1', sa.Float(), nullable=False),
    sa.Column('year_2_semester_2', sa.Float(), nullable=False),
    sa.Column('year_3_semester_1', sa.Float(), nullable=False),
    sa.Column('year_3_semester_2', sa.Float(), nullable=False),
    sa.Column('year_4_semester_1', sa.Float(), nullable=False),
    sa.Column('year_4_semester_2', sa.Float(), nullable=False),
    sa.Column('year_5_semester_1', sa.Float(), nullable=False),
    sa.Column('year_5_semester_2', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wam')
    op.drop_table('shared_graph')
    op.drop_table('gpa')
    op.drop_table('goal')
    op.drop_table('calculations')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
