"""Create calculations, GPA, and WAM tables

Revision ID: ac8998e570b8
Revises: 0fd27ba928a0
Create Date: 2025-05-16 16:01:48.827558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8998e570b8'
down_revision = '0fd27ba928a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculations',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('form_input', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('gpa',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('final_gpa', sa.Float(), nullable=False),
    sa.Column('year_1_semester_1', sa.Float(), nullable=False),
    sa.Column('year_1_semester_2', sa.Float(), nullable=False),
    sa.Column('year_2_semester_1', sa.Float(), nullable=False),
    sa.Column('year_2_semester_2', sa.Float(), nullable=False),
    sa.Column('year_3_semester_1', sa.Float(), nullable=False),
    sa.Column('year_3_semester_2', sa.Float(), nullable=False),
    sa.Column('year_4_semester_1', sa.Float(), nullable=False),
    sa.Column('year_4_semester_2', sa.Float(), nullable=False),
    sa.Column('year_5_semester_1', sa.Float(), nullable=False),
    sa.Column('year_5_semester_2', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('wam',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('final_wam', sa.Float(), nullable=False),
    sa.Column('year_1_semester_1', sa.Float(), nullable=False),
    sa.Column('year_1_semester_2', sa.Float(), nullable=False),
    sa.Column('year_2_semester_1', sa.Float(), nullable=False),
    sa.Column('year_2_semester_2', sa.Float(), nullable=False),
    sa.Column('year_3_semester_1', sa.Float(), nullable=False),
    sa.Column('year_3_semester_2', sa.Float(), nullable=False),
    sa.Column('year_4_semester_1', sa.Float(), nullable=False),
    sa.Column('year_4_semester_2', sa.Float(), nullable=False),
    sa.Column('year_5_semester_1', sa.Float(), nullable=False),
    sa.Column('year_5_semester_2', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('shared_graph', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('shared_with_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_graph', schema=None) as batch_op:
        batch_op.alter_column('shared_with_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    op.drop_table('wam')
    op.drop_table('gpa')
    op.drop_table('calculations')
    # ### end Alembic commands ###
